# docker run -d --name mongodb -p 27017:27017 -e MONGO_INITDB_ROOT_USERNAME=admin -e MONGO_INITDB_ROOT_PASSWORD=password --net mongo-network mongo

services:
  mongodb:
    # container name
    container_name: mongodb
    # exported port(s)
    ports:
      - 27017:27017
    environment: # environment variable(s)
      - MONGO_INITDB_ROOT_USERNAME:admin
      - MONGO_INITDB_ROOT_PASSWORD:password

    image: mongo

  mongo-express: # container name
    image: mongo-express
    ports: # exported port(s)
      - 8080:8080
    environment: # environment variable(s)
      - ME_CONFIG_MONGODB_ADMINUSERNAME:admin
      - ME_CONFIG_MONGODB_ADMINPASSWORD:password
      - ME_CONFIG_MONGODB_SERVER=mongodb
    networks:
      - mongo-network

networks:
  mongo-network:
